pipeline {
pipeline {
    agent any 
    stages {
        stage('Build') { 
            steps {
                sh 'python -m py_compile sources/add2vals.py sources/calc.py' 
                stash(name: 'compiled-results', includes: 'sources/*.py*') 
            }
        }
        stage('Install Dependencies') {
            steps {
                sh 'pip install -r requirements.txt'
            }
        }
        stage('Compile Executable') {
            steps {
                unstash 'compiled-results'
                sh 'pyinstaller --onefile sources/add2vals.py'
            }
        }
        stage('Publish Artifacts') {
            steps {
                archiveArtifacts artifacts: 'dist/add2vals', allowEmptyArchive: true
            }
        }
    }
}

